# .github/workflows/vercel.yml
name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g vercel
      - name: Deploy production
        if: github.ref == 'refs/heads/main'
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy staging
        if: github.ref == 'refs/heads/development'
        run: vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }}
